version: '3.7'

services:
  api:
    image: connect4-rl
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    volumes:
      - ./data/db:/data/db
    image: mongo:4.1.3
    networks:
      - backend

networks:
  backend:
    driver: bridge
