version: '3.7'

services:
  api:
    image: connect4-rl
    ports:
      - "8080:8080"
    volumes:
      - .:/root/connect4-rl
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    image: mongo:4.1.3
    networks:
      - backend

networks:
  backend:
    driver: bridge
